### ISSUE TITLE
Shadowing behaviour?

### ISSUE THREAD

**Issue by bbinet** [resin-os/bindmount#4]
Here is a small question concerning the bindmount tool and its shadowing behavior:
https://github.com/resin-os/bindmount/blob/master/src/main.rs#L34-L35
in case of shadowing, will the shadowed files still be visible in the mounted target directory?

I saw bindmount has been introduced in this commit:
https://github.com/resin-os/meta-resin/commit/63b0f16f2dc9b9f95561249d11835ae98f9d8ea1#diff-282c55f6703b3ec11295d0fc98f75281
but I'm wondering if shadowing behaves in the same way as before with the mount systemd files?

In resinos yocto recipes, how can we add some static files to the state partition (for example a ssh known_hosts file) ?

**Comment by agherzan** [comment]
The shadowing behaviour was not introduced by this tool. This is just a simple wrapper over mount while the mount units (systemd) basically the same.

I'd like to understand a little the problem. Generally, if you want to add static files you just include them in the rootfs. The state partition entries are meant for files/locations which need rw permissions.

**Comment by bbinet** [comment]
This discussion has continued on gitter, so this issue can be closed.
